// Code generated by "stringer -output strings.go -type EntityType,EntityState,ItemType,ObjectType"; DO NOT EDIT.

package rpg

import "fmt"

const _EntityType_name = "SKELETONSKELETON_GUARDDOBJECT"

var _EntityType_index = [...]uint8{0, 8, 22, 29}

func (i EntityType) String() string {
	if i < 0 || i >= EntityType(len(_EntityType_index)-1) {
		return fmt.Sprintf("EntityType(%d)", i)
	}
	return _EntityType_name[_EntityType_index[i]:_EntityType_index[i+1]]
}

const _EntityState_name = "S_IDLES_RUNS_WANDERS_GUARDS_SUSPECTS_HUNT"

var _EntityState_index = [...]uint8{0, 6, 11, 19, 26, 35, 41}

func (i EntityState) String() string {
	if i < 0 || i >= EntityState(len(_EntityState_index)-1) {
		return fmt.Sprintf("EntityState(%d)", i)
	}
	return _EntityState_name[_EntityState_index[i]:_EntityState_index[i+1]]
}

const _ItemType_name = "GOLDPOTIONFOODWEAPONARMORSPECIAL"

var _ItemType_index = [...]uint8{0, 4, 10, 14, 20, 25, 32}

func (i ItemType) String() string {
	i -= 1
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return fmt.Sprintf("ItemType(%d)", i+1)
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}

const _ObjectType_name = "O_TILEO_BLOCKO_INVISIBLEO_SPECIALO_WIN"

var _ObjectType_index = [...]uint8{0, 6, 13, 24, 33, 38}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return fmt.Sprintf("ObjectType(%d)", i)
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
