// Code generated by "stringer -output librpg/common/strings.go -type ObjectType ./librpg/common"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[O_NONE-0]
	_ = x[O_TILE-1]
	_ = x[O_BLOCK-2]
	_ = x[O_INVISIBLE-3]
	_ = x[O_SPECIAL-4]
	_ = x[O_WIN-5]
	_ = x[O_DYNAMIC-6]
}

const _ObjectType_name = "O_NONEO_TILEO_BLOCKO_INVISIBLEO_SPECIALO_WINO_DYNAMIC"

var _ObjectType_index = [...]uint8{0, 6, 12, 19, 30, 39, 44, 53}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
